/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* F:/software/3_11_Diamond_x64/diamond/3.11_x64/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch xo2c00 -type bram -wp 10 -rp 0011 -data_width 2 -num_rows 4 -rdata_width 2 -read_reg1 outreg -gsr DISABLED -reset_rel async -memformat bin -cascade -1 -n pmi_ram_dpXbnonesadr22422411403c7c -pmi -lang verilog  */
/* Tue Nov 05 16:48:11 2019 */


`timescale 1 ns / 1 ps
module pmi_ram_dpXbnonesadr22422411403c7c (WrAddress, RdAddress, Data, 
    WE, RdClock, RdClockEn, Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [1:0] WrAddress;
    input wire [1:0] RdAddress;
    input wire [1:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [1:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.DATA_WIDTH_B = 2 ;
    defparam pmi_ram_dpXbnonesadr22422411403c7c_0_0_0.DATA_WIDTH_A = 2 ;
    DP8KC pmi_ram_dpXbnonesadr22422411403c7c_0_0_0 (.DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(Data[1]), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(Data[0]), .DIA1(scuba_vlo), .DIA0(scuba_vlo), .ADA12(scuba_vlo), 
        .ADA11(scuba_vlo), .ADA10(scuba_vlo), .ADA9(scuba_vlo), .ADA8(scuba_vlo), 
        .ADA7(scuba_vlo), .ADA6(scuba_vlo), .ADA5(scuba_vlo), .ADA4(scuba_vlo), 
        .ADA3(scuba_vlo), .ADA2(WrAddress[1]), .ADA1(WrAddress[0]), .ADA0(scuba_vlo), 
        .CEA(WrClockEn), .OCEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), 
        .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), .DIB8(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), .DIB0(scuba_vlo), 
        .ADB12(scuba_vlo), .ADB11(scuba_vlo), .ADB10(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB8(scuba_vlo), .ADB7(scuba_vlo), .ADB6(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB4(scuba_vlo), .ADB3(scuba_vlo), .ADB2(RdAddress[1]), .ADB1(RdAddress[0]), 
        .ADB0(scuba_vlo), .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), 
        .RSTB(Reset), .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), 
        .DOA2(), .DOA1(), .DOA0(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), .DOB4(), 
        .DOB3(), .DOB2(), .DOB1(Q[1]), .DOB0(Q[0]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr22422411403c7c__PMIP__4__2__2B" */
             /* synthesis MEM_INIT_FILE="" */;



    // exemplar begin
    // exemplar attribute pmi_ram_dpXbnonesadr22422411403c7c_0_0_0 MEM_LPC_FILE pmi_ram_dpXbnonesadr22422411403c7c__PMIP__4__2__2B
    // exemplar attribute pmi_ram_dpXbnonesadr22422411403c7c_0_0_0 MEM_INIT_FILE 
    // exemplar end

endmodule
