/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* Wed Nov 06 09:45:49 2019 */

/* parameterized module instance */
pmi_ram_dpXbnonesadr96951296951211acbc73 __ (.WrAddress( ), 
    .RdAddress( ), .Data( ), .WE( ), .RdClock( ), .RdClockEn( ), 
    .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
