/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* Fri Nov 01 16:29:52 2019 */

/* parameterized module instance */
pmi_ram_dpXbnonesadr11211211401afe __ (.WrAddress( ), .RdAddress( ), 
    .Data( ), .WE( ), .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), 
    .WrClockEn( ), .Q( ));
