/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* Tue Nov 05 16:22:24 2019 */

/* parameterized module instance */
pmi_ram_dpXbnonesadr64951264951211ac94b3 __ (.WrAddress( ), 
    .RdAddress( ), .Data( ), .WE( ), .RdClock( ), .RdClockEn( ), 
    .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
