/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Wed Nov 06 20:26:47 2019 */

/* parameterized module instance */
PLL_75M __ (.CLKI( ), .CLKOP( ));
