/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* Fri Nov 01 17:04:04 2019 */

/* parameterized module instance */
pmi_ram_dpXbnonesadr22422411403c7c __ (.WrAddress( ), .RdAddress( ), 
    .Data( ), .WE( ), .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), 
    .WrClockEn( ), .Q( ));
