/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* Fri Nov 01 10:17:38 2019 */

/* parameterized module instance */
pmi_ram_dpXbnonesadr64825664825611acb529 __ (.WrAddress( ), 
    .RdAddress( ), .Data( ), .WE( ), .RdClock( ), .RdClockEn( ), 
    .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
